print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Dan/Documents/GGJ13/GGJ13/Assets/Art/gate.ma"`)
{		
	file -o "/Users/Dan/Documents/GGJ13/GGJ13/Assets/Art/gate.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Dan/Documents/GGJ13/GGJ13/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/Dan/Documents/GGJ13/GGJ13/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/Dan/Documents/GGJ13/GGJ13/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
